# Generated by Django 6.0.4 on 2026-04-08 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_lead_id_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Sales user assigned to this lead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="city",
            field=models.CharField(help_text="City of residence", max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="electricity_units",
            field=models.PositiveIntegerField(
                help_text="Monthly electricity consumption in units"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(help_text="Full name of the lead", max_length=255),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(help_text="Phone number", max_length=20),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("qualified", "Qualified"),
                    ("site_visit", "Site Visit"),
                    ("proposal", "Proposal"),
                    ("won", "Won"),
                    ("lost", "Lost"),
                ],
                default="new",
                help_text="Current status in sales pipeline",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="lead",
            field=models.ForeignKey(
                help_text="The lead this note belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="crm.lead",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.TextField(help_text="Content of the note"),
        ),
        migrations.AlterField(
            model_name="note",
            name="user",
            field=models.ForeignKey(
                help_text="User who created the note",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
