# Generated by Django 6.0.4 on 2026-04-09 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_alter_lead_assigned_to_alter_lead_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Broadcast subject", max_length=255),
                ),
                ("message", models.TextField(help_text="Broadcast message content")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of recipients"
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        help_text="User who sent the broadcast",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Campaign name", max_length=255)),
                (
                    "source",
                    models.CharField(
                        help_text="Campaign source (e.g., Facebook, Google, Email)",
                        max_length=100,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Campaign budget",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(help_text="Campaign start date")),
                ("end_date", models.DateField(help_text="Campaign end date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the campaign",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EngagementActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("message", "Message"),
                            ("email", "Email"),
                        ],
                        help_text="Type of engagement activity",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the activity"
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="The lead this activity is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_activities",
                        to="crm.lead",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        help_text="User who performed the activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BroadcastRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="crm.broadcast",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts_received",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "unique_together": {("broadcast", "lead")},
            },
        ),
    ]
