# Generated by Django 6.0.4 on 2026-04-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_product_supplier_loan_stock_subsidy_product_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("site_visit", "Site Visit"),
                            ("proposal", "Proposal"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create_task", "Create Task"),
                            ("create_followup", "Create Follow-up"),
                        ],
                        max_length=30,
                    ),
                ),
                ("task_title_template", models.CharField(blank=True, max_length=255)),
                ("task_description_template", models.TextField(blank=True)),
                ("followup_days", models.PositiveIntegerField(default=1)),
                ("followup_notes_template", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CampaignLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_leads",
                        to="crm.campaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_memberships",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "unique_together": {("campaign", "lead")},
            },
        ),
    ]
