# Generated by Django 6.0.4 on 2026-04-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_automationrule_campaignlead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followup",
            name="next_followup_date",
            field=models.DateTimeField(),
        ),
    ]
