# Generated by Django 6.0.4 on 2026-04-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_alter_followup_next_followup_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="contact",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
