# Generated by Django 6.0.4 on 2026-04-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_supplier_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Product display name (e.g. '5kW On-grid')",
                        max_length=255,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        help_text="System capacity in kW (e.g. 3, 5, 10)"
                    ),
                ),
                (
                    "system_type",
                    models.CharField(
                        choices=[
                            ("on_grid", "On-Grid"),
                            ("off_grid", "Off-Grid"),
                            ("hybrid", "Hybrid"),
                        ],
                        help_text="Grid connection type",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Selling price", max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["capacity", "system_type"],
                "unique_together": {("capacity", "system_type")},
            },
        ),
    ]
